### PR TITLE
Fix autotests exec

### PR DESCRIPTION
**Pull request by abbbe**

### CODE REVIEW

**Comment by abbbe** [comment]
@zOrg1331, "make test" does not work for me:

root@0cc241931333:/qsslcaudit/build# make test
Running tests...
Test project /qsslcaudit/build
No tests were found!!!

root@0cc241931333:/qsslcaudit/build# ls -l tests/*[0-9]
-rwxr-xr-x 1 root root 741272 Jan  3 19:50 tests/tests_SslTest02
-rwxr-xr-x 1 root root 737016 Jan  3 19:50 tests/tests_SslTest08
-rwxr-xr-x 1 root root 737016 Jan  3 19:49 tests/tests_SslTest09
-rwxr-xr-x 1 root root 749400 Jan  3 19:50 tests/tests_SslTest12
-rwxr-xr-x 1 root root 719144 Jan  3 19:50 tests/tests_SslTest13
-rwxr-xr-x 1 root root 758536 Jan  3 19:50 tests/tests_SslTest16
-rwxr-xr-x 1 root root 749400 Jan  3 19:50 tests/tests_SslTest19
-rwxr-xr-x 1 root root 749400 Jan  3 19:50 tests/tests_SslTest22

**Comment by abbbe** [comment]
The output above was captured in 16.04:

docker build -t qs-unsafe-xenial -f Dockerfile.qs-unsafe-xenial .
docker run --name qs-unsafe-xenial --rm -it qs-unsafe-xenial

then 'cd build' and run the commands above

**Comment by zOrg1331** [comment]
Thanks, branch updated with a fix.

**Comment by abbbe** [comment]
Ok, original problem seems to be resolved, so I will merge this branch into master and close the issue.
Will use in travis as soon as SSLC-30 gets fixed.

**Pull request merged**
